### PR TITLE
Shader performance optimization: remove atomics and reduce memory writes

### PR DESCRIPTION
**Pull request by tomverbeure**
This patch implements 2 optimizations:

* removal of atomic updates
* only do writes when there's an actual data change
    
GPU atomics are an expensive operation and a limited GPU resource.
The sh_simul shader was using them to flip the D-bit. Since there is already
a memory barrier between each simul stage, and since the D bit of a LUT
that is being simulated will only be used at the earliest in the next
simul stage, there is no need for there to be an atomic update. So
atomicOr and atomicAnd have been replaced by first a read and then a write.
    
In addition, the old code always writes to the D bit even if the D
bit already has the correct value, or copies the D bit to the Q bit even if
the D and Q bit already have the same value. Memory BW is almost certainly 
a bigger bottleneck than shader instruction throughput. So both in sh_simul and
sh_posedge, writes to outputs are now only done if there's a change in value.

Combined, these changes result in a more-than-doubling of the GPU simulation
performance.

### CODE REVIEW

**Comment by sylefeb** [comment]
These are excellent points, thanks for the improvement! 

I actually tried different approaches to remove the glMemoryBarrier(GL_SHADER_STORAGE_BARRIER_BIT) in between stages -- succeeded in the end but the result was an overly complicated (and slower) affair. This is likely when I introduced the atomics, that I did not remove.

Definitely seeing a speed up with your changes. Interestingly on my setup (2080RTX), on silice_blaze (2.7M LUTs) I had 280 usec/cycle, now 250 usec/cycle, so ~10% speedup. On silice_vga_demo, from 40 usec/cycle down to 36 usec/cycle, similar.
But different GPU architectures have very different overheads on atomics in absence of contention.

Thanks again!

**Comment by tomverbeure** [comment]
Interesting that you only see a 10% speedup. I've been running it on an old GTX 1060 which has a lot less memory bandwidth than a 2080. I'll eventually give it a try on my RTX 3070 (when that machine is functional again.)

My real goal is to learn CUDA, get rid of these memory barriers by using CUDA streams for dependent launches so that the CPU is not involved in issuing multiple simul cycles, and add support for memories so they don't need to exploded into individual FFs. But I've been wanting to do that since 2008 (!), so it's a bit of a long term project. But Silixel showed me a way forward that allows me to take it on step-by-step. 

I've tried to run blaze on the 3070 some time ago, but it actually got to the point where it simulated anything: it seemed like it was just hanging. Very strange.

**Comment by sylefeb** [comment]
Just tested on a GTX 980, getting 700 usec/cy vs 841 so 20% speedup in this case. I am under Windows 10 with latest drivers. (OS/drivers might play a role here?)

CUDA streams: that sounds good. It should eliminate all CPU<>GPU overheads on synchs, plus free-up the CPU. However the fundamental issue of having to sync between in-cycle stages (combinational depths) will persist?

A possible approach to increase parallelism would be to overlap cycles: some gates of a stage `s` at cycle `i+1` may depend on the result (Q) of gates at stage `k` of the previous cycle `i`, but not on stages `>k` of `i`. So as soon as `(i,k)` is done, these gates in `(i+1,s)` could be processed. Unsure how much this exists in practice, but there is hope for a finer granularity. Combined with streams, that might provide a significant boost. (Some outputs Q have to be duplicated however, since they can be both input to a next cycle and to a next stage at the same cycle).

Also, it is not clear to me whether to focus the efforts on CPU or GPU, especially since the CPU version could be optimized greatly with SIMD, and parallelized across cores. Regardless, it's interesting to pursue both!

Side note: another reason for the atomics, that I remembered this morning, was to try to pack several LUTs into a same int. If I correctly remember I tried (in the hope to reduce bandwidth) but that wasn't a win in the end (Unsure, should have documented these tests! Also this might have been with a different overall approach, so might still be worth a shot).

**Comment by tomverbeure** [comment]
> Just tested on a GTX 980, getting 700 usec/cy vs 841 so 20% speedup in this case. I am under Windows 10 with latest drivers. (OS/drivers might play a role here?)

Looks like it might be the OS. It'd be interesting to see the differences. I don't have a Windows development environment. Can you post a .exe? I'd love to see the performance difference between Linux and Windows.

> CUDA streams: that sounds good. It should eliminate all CPU<>GPU overheads on synchs, plus free-up the CPU. However the fundamental issue of having to sync between in-cycle stages (combinational depths) will persist?

Yes, that's a fundamental issue that can't really be fixed. Silixel is very neat in that it reduces the problem to just LUT simulation, but that's also a very slow way of doing things. Ideally, you'd use Yosys the CXXRTL way, where you don't break up the design down to LUT granularity but larger building blocks (adders, multipliers etc) that still work at bus level. I don't think anybody has done that for GPUs.

> Side note: another reason for the atomics, that I remembered this morning, was to try to pack several LUTs into a same int.

Yup! I figured as much! 

Tom

**Pull request merged**
